# Generated by Django 5.0.7 on 2024-07-22 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('strike_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('slid', models.AutoField(primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('sl_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField()),
                ('symbol', models.CharField(max_length=5)),
            ],
            options={
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='IsAccessibleBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocksapp.stocklist')),
            ],
            options={
                'unique_together': {('slid', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StockListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField()),
                ('slid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocksapp.stocklist')),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocksapp.stock')),
            ],
            options={
                'unique_together': {('slid', 'symbol')},
            },
        ),
    ]
