# Generated by Django 5.0.7 on 2024-07-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmaPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timestamp', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ema', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
