# Generated by Django 5.0.7 on 2024-08-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocksapp', '0002_emaprediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmaPrediction',
        ),
    ]
